Repository Erol444/TravianBotSharp, pull requests merged in 2021-11, with the labels that each got.

#59 Fix ci cd
  .github/workflows/build.yml
  .github/workflows/pre-release.yml
  .github/workflows/release.yml
  README.md
  TbsCore/Models/Access/Access.cs
  TbsCore/Models/Access/AccessInfo.cs
  TbsCore/TbsCore.csproj
  TbsCore/packages.lock.json
  TravBotSharp/TbsWinForms.csproj
  TravBotSharp/packages.config
Labels: ci-cd

#60 Fix ci cd (#59)
  .github/workflows/build.yml
  .github/workflows/pre-release.yml
  .github/workflows/release.yml
  TbsCore/Models/Access/Access.cs
  TbsCore/Models/Access/AccessInfo.cs
  TbsCore/TbsCore.csproj
  TbsCore/packages.lock.json
  TravBotSharp/TbsWinForms.csproj
  TravBotSharp/packages.config
Labels: release

#65 Fixed check attack spamming in TTwars, fixed github error
  TbsCore/Helpers/GithubHelper.cs
  TbsCore/Tasks/LowLevel/CheckAttacks.cs
Labels: pre-release

#67 Fix navigation
  TbsCore/Helpers/HttpHelper.cs
  TbsCore/Helpers/NavigationHelper.cs
  TbsCore/Helpers/VillageHelper.cs
  TbsCore/Tasks/LowLevel/SendWaves.cs
  TbsCore/Tasks/LowLevel/UpdateVillage.cs
  TbsCore/Tasks/SecondLevel/ScoutPlayer.cs
Labels: pre-release
